# Generated by Django 5.2.4 on 2025-11-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_bonusrequest_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payment_method',
            field=models.CharField(choices=[('vodafone_cash', 'Vodafone Cash'), ('etisalat_cash', 'Etisalat Cash'), ('orange_cash', 'Orange Cash'), ('we_cash', 'WE Cash'), ('bank_transfer', 'تحويل بنكي')], default='vodafone_cash', max_length=20, verbose_name='طريقة السحب'),
        ),
    ]
