# Generated by Django 5.2.4 on 2025-08-02 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_cartitem_marketer_commission_and_more'),
        ('products', '0002_populate_governorates'),
    ]

    operations = [
    ]
