# Generated by Django 5.2.4 on 2025-08-03 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cartitem_marketer_orderitem_marketer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='designer_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='عمولة المصمم'),
        ),
        migrations.AddField(
            model_name='product',
            name='design_ownership',
            field=models.CharField(choices=[('site', 'ملكية الموقع'), ('designer', 'ملكية مصمم')], default='site', max_length=20, verbose_name='ملكية التصميم'),
        ),
        migrations.AddField(
            model_name='product',
            name='designer',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'designer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المصمم'),
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_url', models.URLField(verbose_name='رابط ملف PDF')),
                ('commission_per_sale', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='عمولة البيع لكل قطعة')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('designer', models.ForeignKey(limit_choices_to={'user_type': 'designer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المصمم')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.design', verbose_name='التصميم'),
        ),
    ]
