# Generated by Django 5.2.4 on 2025-08-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cartitem_color_cartitem_size_orderitem_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='روابط الصور الإضافية'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='صورة المنتج الرئيسية'),
        ),
    ]
